// File generated by FlutterFire CLI.
// This is a template - you need to run `flutterfire configure` to generate actual values

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCplkvLQCYQ4wkFnl9xiqHmPoB2mxDn6SM',
    appId: '1:659956454412:web:fa74e076b300b053780a29',
    messagingSenderId: '659956454412',
    projectId: 'appdoanngoll',
    authDomain: 'appdoanngoll.firebaseapp.com',
    storageBucket: 'appdoanngoll.firebasestorage.app',
    databaseURL: 'https://appdoanngoll-default-rtdb.asia-southeast1.firebasedatabase.app',
    measurementId: 'G-NV7Z9WXGB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCplkvLQCYQ4wkFnl9xiqHmPoB2mxDn6SM',
    appId: '1:659956454412:web:499fd7c5430b7a2e780a29',
    messagingSenderId: '659956454412',
    projectId: 'appdoanngoll',
    storageBucket: 'appdoanngoll.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCplkvLQCYQ4wkFnl9xiqHmPoB2mxDn6SM',
    appId: '1:659956454412:web:499fd7c5430b7a2e780a29',
    messagingSenderId: '659956454412',
    projectId: 'appdoanngoll',
    storageBucket: 'appdoanngoll.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCplkvLQCYQ4wkFnl9xiqHmPoB2mxDn6SM',
    appId: '1:659956454412:web:499fd7c5430b7a2e780a29',
    messagingSenderId: '659956454412',
    projectId: 'appdoanngoll',
    storageBucket: 'appdoanngoll.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderingApp',
  );
}
